src/components/Ellipsis/index.js, src/components/Ellipsis/index.less
Update Ellipsis compute through height, fixed: https://github.com/ant-design/ant-design-pro/issues/167
=> Update Ellipsis compute through height

src/components/GlobalHeader/index.js, src/components/GlobalHeader/index.less, src/components/SiderMenu/index.js, src/components/SiderMenu/index.less, src/e2e/home.e2e.js, src/layouts/BasicLayout.js
=> GlobalHeader & SiderMenu

.gitignore, src/components/Charts/TagCloud/index.js
The key point is: `chart.coord().reflect()`.
and you can adjust gaps between words by setting padding
for tag-cloud transform
=> fix(chart): tag cloud overlapping

src/components/GlobalFooter/demo/basic.md, src/components/GlobalFooter/index.js, src/layouts/BasicLayout.js, src/layouts/UserLayout.js
at the moment `title` is incompatible as a key field when using `ReactNode` as the documentation suggests since it translates to `[object Object]`.
this pr holds users responsible for defining unique keys in their `items` prop arrays.
i neglected writing a fallback to using `title` as a key if it is an instance of String, would not mind implementing this for the sake of backwards compatibility. 
any input is appreciated, working with ant is truly a pleasure
=> fix(GlobalFooter): manually define link item keys

.webpackrc, src/common/router.js, src/rollbar.js
Use https://github.com/seeden/babel-plugin-dynamic-import-node-sync
Defaultly, app would be bundled as one file.
The code split will works if you remove `dynamic-import-node-sync` in `.roadhogrc`.
---
close #470
close #524
=> Config code split

src/components/SiderMenu/SiderMenu.js
`BasicLayout` 布局 `SliderMenu` `breakpoint` 目前是失效的，是因为 `isMobile` 的检测
因此，修改为`md => lg` 能够正常触发布局断点，从而能够正常响应布局
=> BasicLayout Slider breakpoint: md => lg

src/components/Login/index.js
当Login内不使用Tab时，存在二个问题：
1、item有可能为空
2、输入框无法输入，执行了Login的render方法，但子组件没有执行
=> 修复当Login内不使用Tab时，输入框无法输入的问题

src/components/PageHeader/index.js
面包屑在某些情况下显示不正确，例如：
新建issue：`/issues/new` ，会被认为 issue详情：`/issues/:id`
=> 修复面包屑显示不正确的问题

src/models/index.js
https://webpack.github.io/docs/context.html The webpack 1.x documentation was deleted.
=> Simplify the code and update the comments

src/components/PageHeader/index.js, src/components/SiderMenu/SiderMenu.js
> 可定义`separator`属性，支持 `string` 和 `element`，可参照 `Ant Design` 面包屑中的 `separator`，功能和参数完全一致
- 直接在 `layouts/PageHeaderLayout` 文件中添加公共分隔符
- 使用 `PageHeaderLayout` 布局独立自定义分隔符
- 在 `components/PageHeader/index.js` 中添加公共分隔符
```
<PageHeader key="pageheader" {...restProps} linkElement={Link} breadcrumbSeparator={<Icon type="swap-right" />} />
```
- 使用 `PageHeaderLayout` 布局组件
```
import PageHeaderLayout from '../../layouts/PageHeaderLayout';
<PageHeaderLayout breadcrumbSeparator={<Icon type="swap-right" />}>
// code...
</PageHeaderLayout>
```
注意：在 `PageHeader` 或 `PageHeaderLayout` 使用 `breadcrumbSeparator` 来自定义分隔符
=>  breadcrumb separator custom

src/components/Authorized/PromiseRender.js
when PromiseRender receivers new props ,the method componentDidMount will not execute ,so 'this.state.component' will not change ,ant it will cause when you change the page ,the component will not change ,so you will get the warning says that 'the Hash history cannot PUSH the same path; a new entry will not be added to the history stack '. and the page will not load correct
=> fix Authorized Promise render recreating

src/layouts/BasicLayout.js
#1098 
访问 '/' 时定向到已授权的第一个页面，而非写死的 'dashboard/analysis'，避免无权限时登录后就定向到 403（或点击 logo 定向到403）
=> fix redirect loop

src/utils/utils.js
In `src/utils/utils.js`
```js
const renderRoutes = renderArr.map((item) => {
const exact = !routes.some(route => route !== item && getRelation(route, item) === 1);
return {
...routerData[`${path}${item}`],
key: `${path}${item}`,
path: `${path}${item}`,
exact,
};
});
```
if i want to reset or custmize exact in `common/router`, it is impossible, because inner exact will cover what i set, so hoist it.
---
and i have a question
if i have two router component named `/room/supervision` and `/room/supervision/:id`
in `utils/utils`  [click here](https://github.com/ant-design/ant-design-pro/blob/master/src/utils/utils.js#L138-L139)
will remove the deep rendering component `/room/supervision/:id`
i want to remove `const renderArr = getRenderArr(routes);`
It looks the same.
=> :bug: fix inner exact cover custom exact bug

src/layouts/BasicLayout.js
现在的面包屑是这样显示的：
这个 PR 会将面包屑优化成这个样子：
完善了面包屑的层级展示。
---
思路是传到 `context` 的 `breadcrumbNameMap` 参数除了包含 `routerData` 里定义的内容外，还添加了 `menuData` 中定义的一些没有在 `routerData` 中定义的父级对象。
=> Improve the display of bread crumbs

src/components/Charts/TimelineChart/index.js
- Use `tickInterval` instead of `tickCount` to  avoid timeline mismatching.
- Change `mask` from `HH:MM` to `HH:mm`, since `MM` means month while `mm` means minutes. (https://momentjs.com/docs/#/displaying/)
Before (https://preview.pro.ant.design/#/dashboard/analysis):
After
=> Fix TimelineChart time format issue

.webpackrc.js, package.json
Close #1347
Close #1346
由于 [babel@7 升级](https://github.com/babel/babel/pull/7734)导致的 break change，`transform-decorators-legacy` 无需引入了。
不删会有这个报错。
```
Property right of AssignmentExpression expected node to be of a type ["Expression"] but instead got null
```
=> fix: babel transform failed with transform-decorators-legacy

src/components/SiderMenu/SiderMenu.js, src/components/SiderMenu/SilderMenu.test.js
The related issue is https://github.com/ant-design/ant-design-pro/issues/1424.
=> Fix functionName typo from getMeunMatcheys to getMeunMatchKeys

src/components/DescriptionList/DescriptionList.js
React throw a exception when you display `DescriptionList.Description`dynamic  like following codes:
Exception: 
`React.cloneElement(...): The argument must be a React element, but you passed null.`
Because it clone each children by React top level API `React.cloneElement` in `DescriptionList` for assign `column` attribute.
Just don't clone falsy children in `DescriptionList` (because a `DescriptionList.Description` will never be a falsy value)
``` javascript
React.Children.map(children, child => child ? React.cloneElement(child, { column }) : child)
```
=> fix React.cloneElement in component DescriptionList

src/components/SiderMenu/SiderMenu.js, src/components/SiderMenu/SilderMenu.test.js
The purpose of `getFlatMenuKeys` is to form a flat array from a nested array so that using `Array.reduce` might be a better approach to concat formatted value to the final result one by one instead of `Array.forEach`.
Using `Array.reduce` also can ensure the formatted flat array remain the same elements order as the original nested array.
For example, if we have the menu data like below:
```javascript
const menu = [{
path: '/dashboard',
children: [{
path: '/dashboard/name',
}],
}, {
path: '/userinfo',
children: [{
path: '/userinfo/:id',
children: [{
path: '/userinfo/:id/info',
}],
}],
}];
```
Before `getFlatMenuKeys` will return
```javascript
[ '/dashboard/name',
'/dashboard',
'/userinfo/:id/info',
'/userinfo/:id',
'/userinfo' ]
```
By using `Array.reduce` we could get
```javascript
[ …
```
=> Improve getFlatMenuKeys & getMeunMatchKeys for better readability and robustness

src/components/Result/index.less, src/routes/Forms/StepForm/Step3.js, src/routes/Forms/StepForm/style.less, src/routes/User/Login.less
Open login page of this project. Then click `Toggle device toolbar` in Chrome devTools and select `iPhone 5/SE` in toolbar
The width of main container in login page be locked(fixed) in `src/routes/User/Login.less` 
Set width to 95%(5% for gap) in small screen resolution device.
``` css
@media screen and (max-width: @screen-sm) {
width: 95%;
}
```
=> fix broken login page on mobile device with small screen resolution

src/layouts/Header.js
修正了 `Header` 在单独使用 `Fixed Header` 时手机端的宽度及同时使用 `Fix Siderbar` 和 `Fixed Header` 时桌面端的宽度问题
=> fix: fixed header width

src/layouts/BasicLayout.js, src/routes/Account/Settings/Info.js
这里没有必要加 `overflow: 'auto'` 这个样式，加了反而会导致原本的 `overflow-x: hidden` 被覆盖掉，使得部分页面（监控页）在某些情况下（宽度较大）出现横向滚动条
=> fix: layout overflow style with fixSiderbar

src/components/HeaderSearch/index.d.ts
在TS中，引入HeaderSearch组件会提示
```
[ts] Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<HeaderSearch> & Readonly<{ children?: ReactNode; }...'.
```
发现在 `ant-design-pro/es/HeaderSearch/index.d.ts` 中IHeaderSearchProps接口中缺少对className的定义。
=> fix: add property className into interface IHeaderSearchProps

src/components/SiderMenu/index.less, src/index.less
修复了 Siderbar 固定时部分页面高度的问题，其实本来都用 `100%` 就可以的，但是 `.root` 这个元素的子元素是一个 `.screen-xx` 这样的一个元素，这个元素没有设置高度，所以 `.ant-layout` 得用 `100vh` 了
=> fix: layout height

src/components/Ellipsis/index.d.ts, src/components/Ellipsis/index.en-US.md, src/components/Ellipsis/index.js, src/components/Ellipsis/index.test.js, src/components/Ellipsis/index.zh-CN.md
whether consider full-width character length as 2 when calculate string length. #1635
=> feature: Ellipsis components add "caculateShowLength" 

src/components/Authorized/CheckPermissions.js, src/components/Authorized/index.md
Promise the execution, The status not again changes. quit & login authority result also not again changes. This is a mistake.
but authority is a function . After performing return Promise. There will be no such problem.
so if authority is a function . After performing return Promise. After performing return Promise is render component, Realize dynamic verification 。
由于 Promise 执行后的状态不可变更，如果 authority 配置 直接传入一个 Promise 来做权限验证时，只会得到第一次执行的结果。退出登录其它帐号，验证也不会改变。
如果在传入函数的情况下，让其返回一个 Promise 就不会存在这个问题。所以在 传入函数时，也验证一次结果是不是 Promise 让它去 渲染 ，从而实现动态验证。
------
我直接将 master 重置成了远端主仓库的版本，然后在 master 重新再改了一遍，再试一次把，抱歉，添麻烦了。
如果不行就只能靠你们自己改一下了？。。 😢
=> feature: add <Authorized/> authority function After performing return Promise is render <PromiseRender/> component

src/utils/utils.js
The reg use global tag will result in wrong judgement because it will remember the lastIndex of the same string, and the reg didn't think about the situation when url with port 
before:
```javascript
isUrl('http://xxx.xxx.xxx')
// => true
isUrl('http://xxx.xxx.xxx')
// => false
isUrl('http://192.168.1.1:8011')
// => false
```
after:
```javascript
isUrl('http://xxx.xxx.xxx')
// => true
isUrl('http://xxx.xxx.xxx')
// => true
isUrl('http://192.168.1.1:8011')
// => true
```
=> fix: isUrl func failed && support judge url with port

.gitignore, src/components/HeaderSearch/index.js
1. 删除无用timeout代码
2. 利用 lodash 中的 debounce 函数增加防抖处理
3. 添加 gitignore 规则，排除 VSC 插件生成的 .history 文件夹
close #1703
=> fix: HeaderSearch组件中添加对 enter 键的防抖处理

src/components/SettingDarwer/index.js
应该在禁用 fixedHeader 属性时禁用 autoHideHeader
=> fix: judgment condition of autoHideHeader state

scripts/mergeLessPlugin.js
在jenkins上跑的时候发现了这个问题。会因为fs.mkdir是异步方法导致报错。
=> mkdir改成同步方法

mock/api.js, mock/chart.js, mock/geographic.js, mock/notices.js, mock/profile.js, mock/rule.js, mock/user.js
https://github.com/ant-design/ant-design-pro/issues/1512
没有做太多的代码修改，调整了一下目录结构。对会阻塞掉运行的一些地方做了简单的修改，便于后续基于该版本快速分工迭代。
该 PR 做的修改有：
- 去掉 roadhog，添加 umi 依赖
- 去掉 dva，添加 umi-plugin-dva 依赖
- 添加 config/config.js 并把 webpackrc.js 合并到里面
- 修改 routes 目录为 pages，并修改对应代码中的引用路径
- 去掉 models/index.js，在 umi 中 models 下的 model 会自动挂载
- `src/index.ejs` 修改为 umi 约定的 s`rc/pages/document.js`
=> feat: migrate to umi

src/components/Charts/Pie/index.less
```
<Pie subTitle="Im subTitle"  />
```
The subTitle don't align to center vertically for `height: 62px` https://github.com/ant-design/ant-design-pro/blob/master/src/components/Charts/Pie/index.less#L64
Pie.total has a css property` transform(-50%, -50%)`, which can calculate position base on the real height, so I think there's no need to lock the height of Pie.total, If want to control the content, max-height is better
=> fix: use max-height to replace height for better vertical-align

src/components/Charts/bizcharts.d.ts, src/components/Charts/bizcharts.js
sometimes need to use both bizChart and antd-pro in project, and If I keep `ant-design-pro` and `bizcharts` the same time in project's `package.json.dependencies`, that will bring multi-version of g2
so export bizcharts using interface like
`import bz from 'ant-design-pro/lib/Charts/bizcharts`
=> feat: export bizcharts

src/components/Charts/TimelineChart/index.d.ts
By watching TimelineChart Example:
[Charts Demo](https://pro.ant.design/components/Charts#scaffold-src-components-Charts-demo-mini-area)
```javascript
const chartData = [];
for (let i = 0; i < 20; i += 1) {
chartData.push({
x: (new Date().getTime()) + (1000 * 60 * 30 * i),
y1: Math.floor(Math.random() * 100) + 1000,
y2: Math.floor(Math.random() * 100) + 10,
});
}
```
1. X-Axis (Timeline): The type should be like `number`.
2. Y-Axis (Value): The y2 may not be required if I just want to draw y1 only.
=> [BugFix] Fix chart data type and requirement

package.json
"react-loadable" should not be DEV dependencies because it be used in "src/common/router.js"
=> Move "react-loadable" to dependencies

src/components/Charts/Pie/index.d.ts
the property colors?: string[] was missing in the typescript definitions
=> Add missing colors prop in Pie Chart index.d.ts

src/layouts/BasicLayout.js
首次匹配终止循环，提高性能并避免被二次相似规则匹配覆盖,如：
```
/basic/deal/pubservice
```
```
/basic/deal/:id
```
=> fix title: Break the loop and avoid being overwritten

config/config.js, package.json
* dll 配置不对
* dll 需 exclude `@babel/runtime`
* `umi dev` 时现在不能启用 `ANALYZE=1`，因为 dll 也会开启，待 umi 修复这个问题后再考虑
=> fix: dll and analyze

config/config.js, package.json, src/global.js
应用应该不用自己引 polyfill。
@chenshuai2144 可以说下加这个为了啥。
@sorrycc 看看有什么问题。
---
如果是解决 https://github.com/ant-design/ant-design-pro/issues/2125 的 Number.isNaN 的问题，@sorrycc 看看是不是 polyfills ie9 或者 ie11 里面漏了。
=> remove babel polyfill

src/components/Authorized/index.d.ts
`AuthorizedProps` is missing from module's exports.
=> fix: Export AuthorizedProps

src/pages/List/Applications.js, src/pages/List/Articles.js, src/pages/List/List.js, src/pages/List/Projects.js
close #2196 
- 场景：这里的表单是表格上方的筛选项，不是通常意义下用提交按钮统一提交的表单，是需要在每一个表单项变化时触发 action 去取新的表格数据。
- 之前的实现：之前的做法是在每一个表单元素上绑定 onChange，在 onChange 里调用 form.validateFields 去取所有的表单项。
- 问题：需要在 setTimeout 后调用 validateFields，因为 onChange 事件是每个表单元素本身的变化时触发，时机在 form 状态改变之前。不使用 setTimeout 的话，会拿不到所有数据。
使用 form 的 `onValuesChange` 进行监听。
=> using onValuesChange instead of binding onChange

src/components/Charts/Pie/index.js
我使用percent这个属性值为0时饼图不显示，所以我之前改了一下
https://github.com/ant-design/ant-design-pro/pull/2282/commits/c69c1d4118c6d36cef228d52da8504a68acc35ee
我漏改了一处，虽然API文档没提data，但Pie能接受data这个属性而且有人在用了，如果按我之前的改法，那就需要percent不能有默认值，否则不传percent，perconet默认值为0了，后面的逻辑会覆盖掉用户传的data
=> fix: Pie chart percent prop default value

src/components/Login/LoginItem.js
this.customprops并不存在，而是通过props传入到组件里的，所以应该是用this.props.customprops获取，而不应该是this.customprops。
=> 修改getFormItemOptions方法中customprops的错误

src/components/TopNavHeader/index.js
当屏幕过小时（13.3寸），菜单过多时，会把语言切换按钮挤到下一行；
layout为topmenu
=> topmenu模式，菜单过多时，切换语言按钮不显示

src/components/SiderMenu/BaseMenu.js, src/components/SiderMenu/index.less
Fixes #2182 
add a class named 'top-nave-menu' when BaseMenu mode is horizontal to fixed height promblem
Before:
After:
=> fix (#2182): top menu layout without submenu display issue

.eslintrc.js, src/components/Login/index.less, src/components/SiderMenu/SiderMenu.js
fix #2475 #2445 
> 1. 将主题设为亮色，固定头部和固定侧边栏时，侧边栏出现横向滚动条
=> fix: (#2475, #2445) input box-shadow for login page

src/pages/Account/Center/Articles.js
Add a space between `href` and `text` in the articles of Account Center page.
Makes it a bit more comfortable right ?
Before:
After:
=> tweak the space between href

src/pages/Dashboard/Analysis.js
最近在使用`antd-pro`时发现分析页一个排名列表样式好像漏了点什么
这是销售额排名排名：
访问量排名：
不知道是不是原本就是这样设计的，不过既然两个列表从各种方面来说都是并列的，样式统一会不会比较好？
修改后的访问量排名：
=> style: better analysis page ranking list style

src/pages/404.js
When switching locale, the `404` page renders text wrongly.
The `desc` and `backText` props should be provided to properly respond to different locales.
After modification, it works:
=> Fixed 404 page error

config/router.config.js
This was caused by extra name in router.config.js.
'/form/step-form' is a pure redirect route and shouldn't have name,
like other redirect routes
=> Fixed 'menu.form.stepform.stepform' not found in locale error

src/components/Login/index.js
when the children is object.
when the children is array.
`[...children] should be changed the `children` for self-defined.
=> fixed the login component not pass the object children

src/layouts/Header.js
reproduce steps in [preview](https://preview.pro.ant.design/dashboard/analysis?fixedHeader=1&autoHideHeader=1):
1. switch on fixed header
1. switch on hide header when scroll down
1. scroll down much!!
1. scroll up once
1. header show and immediately hide
=> fix header will be visible and then immediately hide when scroll up

src/components/TagSelect/index.js
Using **TagSelect** in the **Form** component, the value of **TagSelect** can‘t be cleared when running `resetFields`.
=> Fixed TagSelect can't clear value when Form run resetFields

src/layouts/BasicLayout.js
加上 router.path 为空的判断是因为我发现实际 routeData 会存在没有 path 的状况
Close: #3084
=> fix: 解决当 path 带有参数信息时，会导致权限判断失效

src/components/SiderMenu/BaseMenu.js
collapsed 为false时，刷新后菜单的openKeys为[]时，导致菜单不展开的问题
=> fix: reload menu open question

src/components/HeaderDropdown/index.less
#3079 
.container > *:global(:not(.ant-dropdown-menu)){}自动被编译成了:not(.ant-dropdown-menu){}
=> fix: less compile bug

src/components/HeaderSearch/index.js
修复 #3222  问题，在使用 HeaderSearch组件时，可以选择使用 `onSearch` 或者 `onChange ` 方法。
使用方式：
```
<HeaderSearch
className={`${styles.action} ${styles.search}`}
placeholder={formatMessage({ id: 'component.globalHeader.search' })}
dataSource={[
formatMessage({ id: 'component.globalHeader.search.example1' }),
formatMessage({ id: 'component.globalHeader.search.example2' }),
formatMessage({ id: 'component.globalHeader.search.example3' }),
]}
onSearch={value => {
console.log('search-input', value); // eslint-disable-line
}}
onChange={value => {
console.log('change-input', value); // eslint-disable-line
}}
onPressEnter={value => {
console.log('enter', value); // eslint-disable-line
}}
/>
```
=> 修复 HeaderSearch 的 onSearch 回调

src/components/Ellipsis/index.d.ts
cutStrByFullLength should be string
=> fix: Ellipsis types

src/components/NoticeIcon/NoticeIconTab.d.ts
The attribute `skeletonProps` in NoticeIcon tab has default value of `{}` so it doesn't necessary have to be required as stated in typings. This PR fixes it be optional.
=> Fix NoticeIcon tab typings for skeletonProps

src/pages/List/BasicList.js
the model will show "编辑订单" in the title even if a user clicks on the "+" because the `current` variable has a default `{}` in the assignment. We should check `current.id` to decide the model title copy.
before:
after:
=> Fix an issue in list item Add

src/pages/document.ejs
Error parsing a meta element's content: ';' is not a valid key-value pair separator. Please use ',' instead.
=> fix viewport content

src/components/SiderMenu/SiderMenu.js
When first visit the page, submenu is expanded. When refresh the page, the submenu collapsed.
=> Fix submenu collapsed when refresh page

src/components/SiderMenu/SiderMenu.js, src/layouts/BasicLayout.js
Collapse button had to be pressed twice after resizing to mobile. Fixes this issue along with removing some of the dodgy code that caused the Sider to quickly open and close upon refresh of the page on mobile.
=> fix: unresponsive collapse btn on mobile

config/config.js, src/defaultSettings.js, src/global.js
Add configuration to quickly close pwa
=> feat: support pwa config

src/components/SiderMenu/BaseMenu.js, src/components/SiderMenu/index.less
当菜单图标采用url方式引入且菜单折叠时文字不隐藏，如下图所示
=> fix customize menu icon bug

package.json, src/components/Authorized/AuthorizedRoute.d.ts, src/components/Charts/index.d.ts, src/components/HeaderDropdown/index.d.ts, src/components/Login/LoginItem.d.ts
Support for typescript types declaration.
=> Fix missing export default 

.eslintrc.js
解决当需要在mock文件夹下建立子文件夹时，Eslint的警告问题。
=> fix: Eslint warning of Mock dependence

config/router.config.js, src/layouts/BasicLayout.js, src/models/menu.js, src/pages/Authorized.js
1、把权限路由从布局里面中移除，感觉更加规范一点。
2、menu中新增了一个routerData，用于保存从配置或者服务端下发的原始的路由数据。
3、在权限路由中判断路由的权限和是否登录，感觉更贴合实际的使用场景。
4、删除了路由配置中根目录的权限设置，因为现在权限有继承关系。
5、注意：高级表单页面的权限有在runtime里面做了权限追加，所以登录user时，有访问权限，可以使用高级详情页，测试权限路由可用。/profile/advanced
其实如果动态菜单和动态权限都从服务端获取的话，那menuData和routerData大概长这样子：
```js
menuData:{
routes: [
// dashboard
{
path: '/dashboard',
name: 'dashboard',
icon: 'dashboard',
routes: [
{
path: '/dashboard/analysis',
name: 'analysis',
},
{
path: '/dashboard/monitor',
name: 'monitor',
},
{
path: '/dashboard/workplace',
name: 'workplace',
},
],
},
]
}
```
```js
routerData:{
routes: [
// dashboard
{
path: '/dashboard',
authority: ['admin'],
routes: [
{
path: '/dashboard/analysis',
authority: ['admin','user'],
},
],
},
]
}
```
保持原来的配置写法也可以。
=> Use Umi Permission Routing

src/models/menu.js
When hideInMenu is set to true in router.config.js, these hidden menus are not included in the breadcrumbNameMap, causing the breadcrumbs to appear empty. This commit fixes this problem.
=> fix the problem that breadcrumbNameMap does not contain hidden menus.

src/components/DescriptionList/index.less
The text in a Description item could be wrapped when it's long enough causing DescriptionList style messes up. In this case using several DescriptionList one after one will be a solution. 
This pull request will fix the margin top error on the DescriptionList when it's following another DescriptionList.
=> Fix style error of DescriptionList following DescriptionList

src/pages/Authorized.js
当前权限功能存在无法继承父权限的Bug。
eg: 对于下述权限配置，``/form/form1``无法继承到``/form``的``['admin', 'user']``权限，而返回的是undefined
```js
{
path: '/form',
icon: 'form',
name: 'form',
authority: ['admin', 'user'],
routes: [
{
path: '/form/form1',
name: 'form1',
component: './Forms/Form1',
},
{
path: '/form/form2',
name: 'advancedform',
component: './Forms/Form2',
authority: ['admin'],
},
],
},
```
其原因是``getRouteAuthority()``函数在递归返回的时候，未判断权限为空的情况。
=> Fix authoriy inherit issue

config/config.js, config/plugin.config.js
https://github.com/ant-design/ant-design-pro/issues/3649
现有的解决包太大的问题的方法是把资源依赖移到了外面去了（用到了阿里的CDN）。某种程度上不是好选择，因为这样整个项目多了一个奇怪的依赖，如果没有互联网都没办法开发。而且还会需要单独设置csp来对付两个站外文件。
以下的代码如果进了“plugin.config.js”后会把相应的package或者sub package移到单独的文件。我根据现有的analyze，根据文件大小和相互之间的逻辑关联度，手动做了一个分类。虽然这样做不能减少包的总大小，但是有助于让不太经常需要的包单独成chunk（例如dataset和bizchart这种，会在带图标的页面异步加载）。
https://github.com/ant-design/ant-design-pro/pull/3650/files
现有版本（两个站外文件）：
现有版本（把站外文件拿回来）：
按建议分块：
总结：这个变化的核心思想是：
1. 把两个外链干掉，使用纯正的npm封装和依赖。
2. 把很多时候不一定要用到的包移到单独的chunk里面进行异步加载。
3. 建立一个可以给未来使用的chunk封装方法。
比较一下几个方案
|                          | umi.js   | vendors.js | total  | external |
|--------------------------|----------|------------|--------|----------|
| Current                  | 1.23MB   | 876.4KB    | 2.34MB | 2 files  |
| Current without External | …
=> Optimize asset chunking

src/components/TopNavHeader/index.js
"顶部菜单布局"且内容区域宽度为“定宽”时，若屏幕尺寸小于1200，顶部菜单右侧内容被遮挡。
=> fix:小屏幕显示不完全

config/config.js
将./src/defaultSettings.js中pwa设置false时，‘umi-plugin-react’中pwa配置项的值应该是false；使用空对象{}依旧会开启 PWA 相关功能。
=> Fix：pwa配置项

src/components/Charts/MiniProgress/index.d.ts, src/components/Charts/MiniProgress/index.js, src/locales/en-US/component.js, src/locales/pt-BR/component.js, src/locales/zh-CN/component.js, src/locales/zh-TW/component.js
An _optional_ property for the component **MiniProgress** which will be used as the label for the **Tooltip**. In case of the value of the _prop_ isn't defined, a default _internationalized_ message will be used.
Those modifications were planned based on the issue [Can't Remove MiniProgress tooltip #3761 ](https://github.com/ant-design/ant-design-pro/issues/3761).
=> Optional prop which is used as label for Tooltip #3761

config/config.js
官方的网站打开 sourcemap，方便定位一些编译之后的错误
The official website opens sourcemap, which is convenient for locating some errors after compilation.
=> add source map in site

src/utils/Authorized.js
This is causing a redirect issue after login attempts.
'RenderAuthorized' should be 'RenderAuthorize'
=> Spell mistake in Authorized util.

src/components/PageHeaderWrapper/index.js, src/components/PageHeaderWrapper/index.less
- PageHeaderWrapper width adjusted by contentWidth
- new fluid prop to make PageHeaderWrapper fluid independently of contentWidth
- logo side by side with title
- home={null} working again
=> PageHeaderWrapper: fixed width, logo and home 

package.json
目前 umi-create 使用 fork 的 repo: https://github.com/umijs/ant-design-pro
在 package.json 中添加 ignore files，从而解耦 fork repo 保持 repo 同步。
合并后会更新 `create-umi` 指向 https://github.com/ant-design/ant-design-pro 并读取 ignore file 进行删除保持代码纯粹性。
=> feat: Add ignore file in package.json

create-umi/package.json, package.json
=> fix #4311 lint error in windows

package.json
The scripts `lint:style` used stylelint but that is missing package.json
=> fix missing stylelint in package.json

src/pages/Authorized.tsx
Paths of same prefix will return the last match. It will occurs problem as follows:
Routes:
```{
path: '/',
authority: ['admin', 'user']
routes: [
{
path: '/prefix2',
authority: ['user']
},
{
path: '/prefix',
authority: ['admin']
},
]
}
```
Problem：
When user visit the '/prefix2', it will match the '/prefix', then Exception403 occurs.
=> fix: paths of same prefix problem.

Dockerfile.hub
docker-hub在构建镜像之前需要依赖项目已经打包到dist目录，否则报错
=> modify docker-hub:build

src/components/NoticeIcon/index.tsx
antd 会给 overlay 中的 node 注入一些 props。spin 会原封不动的继承。然后渲染在 dom 上。但其实是不需要的
close https://github.com/ant-design/ant-design-pro/issues/4658
https://github.com/ant-design/ant-design/blob/65eb713fe897f65bbf187e215c664e5f9b468252/components/dropdown/dropdown.tsx#L109
=> fix: fix NoticeIcon dev warning

package.json
package中配置为
"lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
所以src以外报错是没有提示的，然后提交也提交不了。
修改为
"lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./",
能够看到错误，修改后正常提交
close #4720
=> fix: lint:js path

src/components/GlobalHeader/index.less
修改`GlobalHeader`中`RightContent`在`dark`和`topmenu`模式下, 
`@media only screen and (max-width: @screen-md)`( 注:`768px`)的样式错误
[官方演示demo](https://preview.pro.ant.design/dashboard/analysis?language=zh-CN&layout=topmenu&contentWidth=Fixed)
=> 修复GlobalHeader中RightContent样式问题

package.json
使用create umi建立项目不需要CNAME文件
close #5205
=> fix: 通过create umi创建项目可能不需要CNAME

src/layouts/SecurityLayout.tsx
项目里想要实现基于 JWT 的鉴权功能，当 token 没有时跳转到登录页，发现最新的代码里面已经添加了 SecurityLayout 去实现该功能，觉得很不错，优化了一下能够实现登录后重定向到之前访问的页面。
1. 添加了 redirect query string
2. 将判断是否登录用 isLogin 变量保存并添加注释
=> optimize SecurityLayout

src/components/GlobalHeader/index.less
在 `@media only screen and (max-width: 768px)` 分辨率下，消息 `icon` 的颜色与背景色冲突
**重现步骤：**
- 手机模式下打开官方演示网站
- 设置中选择 `暗色菜单风格` & `顶部菜单布局`
close https://github.com/ant-design/ant-design-pro/issues/5192
=> fix: GlobalHeader styles

src/components/GlobalHeader/index.less
topmenu 情况下，right content 作为 flex item，`float: right` 无效。设置 margin 来实现**靠右**
=> fix: right-align the right content of topmenu

package.json
There are three packages are used in production environment but declared in devDependencies.
Now put them into dependencies. 
close #5410
=> fix:rationalize dependencies and devDependencies in package.json

src/models/login.ts
If pass `javascript:alert(1);//` to `redirect` param in login action, victim can execute javascript code after login.
This patch fixes this vulnerability by redirecting the user to the self-origin site only.
POC: 
`https://preview.pro.ant.design/user/login?redirect=javascript:alert(1);//`
=> Fix: Reflected XSS Vulnerability in login after-action script

docker/nginx.conf
部署后css的content type为test/plain导致页面无法正常渲染css，需要修改nginx配置。
=> 修改docker nginx配置

src/layouts/BasicLayout.tsx
Without `menuHeaderRender`, `ProLayout` would render a HTML anchor link using `<a href="..."></a>` consequently resulting in a page redirection when the user clicks the logo icon.
Therefore, this PR, which uses `menuHeaderRender` in `ProLayout` to render a `<Link>...</Link>` instead, avoids this page redirection and hence results in a better user experience.
=> Use menuHeaderRender in ProLayout to render Link

README.fr-FR.md, README.ja-JP.md, README.md, README.pt-BR.md, README.ru-RU.md, README.tr-TR.md, README.zh-CN.md
Use bash
1. 'npm create umi' needs to be run in an empty folder;
2. During the 'husky' installation, if it is not a git repository, an error will be reported, so run 'git init'.
-----
[View rendered README.fr-FR.md](https://github.com/forijk/ant-design-pro/blob/fix-doc-use-bash-error/README.fr-FR.md)
[View rendered README.ja-JP.md](https://github.com/forijk/ant-design-pro/blob/fix-doc-use-bash-error/README.ja-JP.md)
[View rendered README.md](https://github.com/forijk/ant-design-pro/blob/fix-doc-use-bash-error/README.md)
[View rendered README.pt-BR.md](https://github.com/forijk/ant-design-pro/blob/fix-doc-use-bash-error/README.pt-BR.md)
[View rendered README.ru-RU.md](https://github.com/forijk/ant-design-pro/blob/fix-doc-use-bash-error/README.ru-RU.md)
[View rendered …
=> doc: fix Use bash error.

src/pages/Authorized.tsx, src/utils/utils.test.ts, src/utils/utils.ts
- 修复了 authority 会被后面的 route 覆盖的问题，`authorities` 需要 path 匹配后进行赋值
- 增强了 path 匹配策略，使用 `/` 作为分隔符来区分层级，以避免 `/nested/users` 被 `/nested/user` 匹配的问题
- 增加了测试代码，用来测试继承、覆盖、子串的情况
=> fix: authority covered by routes behind

src/components/NoticeIcon/index.tsx
React.Children.map 会改变key，导致NoticeIcon组件onTabChange无法得到预期的key
=> bugfix: NoticeIcon Tabs activeKey error

package.json
#5907 
https://github.com/okonet/lint-staged/releases/tag/v10.0.0
Prior to version 10, tasks had to manually include git add as the final step. This behavior has been integrated into lint-staged itself in order to prevent race conditions with multiple tasks editing the same files. If lint-staged detects git add in task configurations, it will show a warning in the console. Please remove git add from your configuration after upgrading.
=> remove git add for lint-staged hook

config/config.ts
close #6306 
umi内置了默认为 “” 的 title，
导致每次切换页面时，在pro-layout更改完title后，umi又改为“”，
根据[umi官方配置文档](https://umijs.org/config#title)关闭了内置的title更新
=> 禁用umi.js内置的 title 渲染机制

.github/workflows/deploy.yml, src/pages/user/login/index.tsx
**期望**：切换不同权限的账户登录后，路由鉴权重新加载
**实际**：使用history跳转页面，refresh()后，路由鉴权并没有正常加载，仍然是读的缓存数据。
**解决方案**：
修改登录成功后跳转的方式，使用浏览器自带的window.location.href跳转。
同时兼容非根目录部署的情况。
页面重新加载后，鉴权正常。
=> :bug: 修复切换不同权限的账户登录后，access的鉴权不生效问题

src/utils/utils.ts
例如 http://www.baidu.com?code=081kwzU70XCmVB1RkmW70vvYU70kwzU9&state=STATE#/wechat-auth 中state参数会被解析成STATE#/wechat-auth
=> 修改hash路由下search参数在hash之前，search最后一个参数错误bug

src/pages/user/login/index.tsx
例如 在 http://localhost:8000/#/account/settings 退出，再登录
会跳转到 http://localhost:8000/account/settings#/welcome
正确的情况下应该跳回 http://localhost:8000/#/account/settings
=> config.js里面 history.type 为 hash时，退出重登录后，拼接返回路径时，#号前路径会重复

.github/workflows/deploy.yml, package.json, src/pages/ListTableList/index.tsx
可以与 table 公用配置
```tsx
<ProDescriptions<TableListItem>
column={2}
title={row?.name}
request={async () => ({
data: row || {},
})}
params={{
id: row?.name,
}}
columns={columns}
/>;
```
=> 💥 feat: add pro-descriptions demos 

.github/workflows/preview.yml
解决第一次 push 时 PR 还没有创建拿不到 pr.number 的问题。
afc163/surge-preview#13
=>  chore: run PR preview on pull_request 

tsconfig.json
我在使用的时候，遇到了这个eslint问题
https://github.com/ant-design/ant-design-pro/issues/7540
根据作者提升修复了这个问题，提个MR，解决一下这个问题
=> feat: 修复eslint中mock文件未被引用的报错

.github/workflows/preview.yml
修复部署了原始分支而不是 PR 所在分支的问题。
https://github.com/afc163/surge-preview/issues/62
=> fix: surge preview

README.ar-DZ.md
English docs in README.ar-DZ.md was `[English](./README.zh-CN.md)`. So, I replaced it with `[English](./README.md)`.
-----
[View rendered README.ar-DZ.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.ar-DZ.md)
=> fix English README link

.github/workflows/issue-open-check.yml
只对新开的 issue 进行校验，当用户修改 issue 后，若标题仍校验为空，则不再触发二次评论
还有一种方案是 校验 issue 的状态为 open 的时候，就怕遇到，新开 issue 标题有，然后 用户又把标题删了的。。。不过很少有这种吧
=> ci: update issue-open-check.yml

README.md
Ant Design Pro V5 is not released yet.
`trial` is often used for released paid product, and `preview` is the regularly used word for pre-release version.
-----
[View rendered README.md](https://github.com/ShinChven/ant-design-pro/blob/patch-1/README.md)
=> Update README.md to correct description

README.ar-DZ.md, README.fr-FR.md, README.ja-JP.md, README.md, README.pt-BR.md, README.ru-RU.md, README.tr-TR.md, README.zh-CN.md
I changed language names to countries' flags like this :
Please let me know your thought if this is acceptable or not, thank you.
-----
[View rendered README.ar-DZ.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.ar-DZ.md)
[View rendered README.fr-FR.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.fr-FR.md)
[View rendered README.ja-JP.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.ja-JP.md)
[View rendered README.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.md)
[View rendered README.pt-BR.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.pt-BR.md)
[View rendered README.ru-RU.md](https://github.com/kevinadhiguna/ant-design-pro/blob/master/README.ru-RU.md)
[View rendered …
=> change language names to countries' flags

mock/listTableList.ts
This API is deprecated. Changed to WHATWG URL API using `new URLSearchParams`
Currently PR to master branch, let me know if you hope to merge this into v5 branch instead.
Let me know if there are potential problems with my approach to remove this deprecated method call.
=> Remove deprecated `url.parse`

package.json
WARN  deprecated @types/classnames@2.3.1: This is a stub types definition. classnames provides its own type definitions, so you do not need this installed.
=> Remove deprecated @types/classnames

tests/beforeTest.js
Here is trying to detect which package manager is used by check lock file, however, we got an incorrect directory. Currently, even use yarn to install packages and yarn.lock is existed. still use npm to install puppeteer.
BTW, a minor typo is corrected.
=> fix: detect package manager in wrong directory

src/pages/list/table-list/_mock.ts
detect params.sorter's value before parsing it
=> fix: detect sorter's value first(#8979)

jsconfig.json
js项目如果react组件引用缺少/index  vscode无法导航到定义
=> 修复vscode点击代码引用不会跳转到组件

.stylelintrc.js
使用原来的写法 Webstorm 的 stylelint 插件会找不到配置文件。
应该是 pnpm 没有扁平化安装依赖导致的，用 extends 语法就能解决
=> fix: 修复 fabric.stylelint 与 IDE 的兼容问题

config/routes.ts
Solve the problem of incorrect jumping of secondary menu.
Menu items that contain secondary menus should not have components of their own, which would cause the secondary menu to not jump correctly. For first time users, this is a difficult problem to troubleshoot.
=> Solve the problem of incorrect jumping of secondary menu.

.github/workflows/ci.yml, .github/workflows/preview-build.yml, .github/workflows/preview-deploy.yml, .github/workflows/preview-start.yml, .github/workflows/rebase.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

config/routes.ts
使用了umi4，旧的404页面的route配置方法无法生效，需要加个path为'*'
=> fix: route匹配404页面

.gitignore, .vscode/extensions.json, .vscode/settings.json
脚手架不应该上传编辑器的配置，不是vscode编辑器这个文件就是多余的。
之前5.0也没有这个
=> fix: 多余的文件

src/components/RightContent/index.tsx
build (16.x, ubuntu-latest): src/components/RightContent/index.tsx#L1 This condition will always return 'false' since the types '"light" | "realDark" | undefined' and '"dark"' have no overlap.
https://github.com/ant-design/ant-design-pro/pull/10209/files#annotation_4543727834
=> fix: RightContent 中的 navTheme 条件值

src/locales/en-US/pages.ts
=> Correct spelling

src/app.tsx
Use `history.location.pathname` instead of `window.location.pathname` to support hash router.
=> fix: Hash router is ignored in getInitialState()

config/config.ts
=> fix: 修复antd5时间选择器语言包中文缺失问题

package.json
If I initial my project by execute: pnpm install (not the npm install), Then use git commit, it'll always result an error:
✔ Preparing...
✔ Running tasks...
✔ Applying modifications...
✔ Cleaning up...
npm ERR! could not determine executable to run
npm ERR! A complete log of this run can be found in: husky - commit-msg hook exited with code 1 (error)
so I add a missed dev-depency: @umijs/facrib, It's solved.
=> fix(husky): Prevent the verify error on commit.

src/components/HeaderDropdown/index.tsx
`token.screenXS`是`number`类型，在@media里需要后面加上`px`才能work。
=> fix: HeaderDropdown @media css not working

src/services/ant-design-pro/api.ts
Currently, the query table throws an error during modification and deletion. When adding new entries, the parameters also cannot be passed correctly. 
Based on the definition in `mock\listTableList.ts`, the method of passing request parameters needs to be changed.
```js
function postRule(req: Request, res: Response, u: string, b: Request) {
const body = (b && b.body) || req.body;
const { method, name, desc, key } = body;
switch (method) {
case 'delete':
break;
case 'post':
return;
case 'update':
return;
default:
break;
}
}
export default {
'GET /api/rule': getRule,
'POST /api/rule': postRule,
};
```
=> fix: api.ts Change the parameter passing method

package.json, src/pages/dashboard/analysis/components/IntroduceRow.tsx, src/pages/dashboard/analysis/components/OfflineData.tsx, src/pages/dashboard/analysis/components/ProportionSales.tsx, src/pages/dashboard/analysis/components/SalesCard.tsx, src/pages/dashboard/analysis/components/TopSearch.tsx, src/pages/dashboard/monitor/components/ActiveChart/index.tsx, src/pages/dashboard/monitor/index.tsx, src/pages/dashboard/workplace/index.tsx
1. 升级 charts 到最新版本 plots
> beta.1 发布后生效，目前已经发布的是 beta.0，依赖 G2 的发布
=> chore: upgrade charts

package.json
在 `package.json` 中，提供了 `"serve": "umi-serve"` 命令，却没有添加 `umi-serve` 依赖，会导致运行该命令时出现 `umi-serve: not found` 错误。
根据 commit 历史，可以在此版本中该依赖还是在的： https://github.com/ant-design/ant-design-pro/blob/5963d69f904223ace1c2d579811b21e2daed5a7a/package.json#L85
=> fix: add umi-serve in package.json

config/routes.ts
为 404 路由添加通配 `path`，避免在启用 `exportStatic` 时报错
=> chore: add path for 404 routes

config/routes.ts
Fixed error: Absolute route path "/*" nested under path "/user" is not valid. An absolute child route path must start with the combined path of all its parent routes.
=> Fix blank page error after `npm start`

src/pages/dashboard/workplace/index.tsx
| Before | After |
| ------- | ------ |
| ![image](https://github.com/user-attachments/assets/9940be39-dc4d-4a3a-a85f-3a11a69aad70) | ![image](https://github.com/user-attachments/assets/296f1f7c-5621-4b04-a62f-ddb9c8de0598) |
description过短时无法撑开导致布局错位
=> fix: adjusting workplace project notice card style
