ant-design/ant-design-pro

package.json

Lint staged

---

.roadhogrc
package.json
src/components/EditableLinkGroup/index.js
src/components/Exception/index.js
src/components/Exception/index.md
src/components/GlobalFooter/index.less
src/components/PageHeader/index.js
src/components/PageHeader/index.md
src/layouts/PageHeaderLayout.js
src/routes/Dashboard/Workplace.js
src/routes/Exception/403.js
src/routes/Exception/404.js
src/routes/Exception/500.js

https://github.com/ant-design/test2/commit/9867f6e6e5c6ad03b3125089175b260bb12f2128

Remove dva from component

---

package.json
src/components/Charts/Pie/index.js
src/components/Charts/Pie/index.less
src/components/Charts/index.md
src/routes/Dashboard/Analysis.js
src/routes/Dashboard/Monitor.js

Better pie responsive

---

README.md
appveyor.yml
tests/run-tests.js

For windows
https://github.com/ant-design/ant-design-pro/issues/83

CI in windows

---

.roadhogrc

Use es module

---

src/components/Ellipsis/demo/cover.md
src/components/Ellipsis/demo/height.md
src/components/Ellipsis/demo/line.md
src/components/Ellipsis/demo/number.md
src/components/Ellipsis/index.js
src/components/Ellipsis/index.less
src/components/Ellipsis/index.md
src/routes/List/CardList.js

Add Ellipsis Component

---

src/layouts/BasicLayout.js

Fix submenu-mode error

---

src/components/Ellipsis/index.js

fixed isSupportLineClamp’s judgment

fixed isSupportLineClamp’s judgment

---

src/routes/Forms/StepForm/Step1.js

In step1, user changes some inputs, then clicks next step to step2.  Then, back to step1, user's inputs will lose. fix it.

fix user input information lose

---

src/models/global.js

Reorder the process in "clearNotices" #265

fixed clearNotices effects in global model

---

package.json
src/index.js
src/raven.js
src/rollbar.js

Use https://rollbar.com/afc163/ant-design/ cause it is free to invite members.

Replace sentry with rollbar

---

src/models/global.js

fix bug in effects: `fetchNotices`, after fetching new notices, we should update notice count in user model.

fix updating badge bug

---

src/layouts/BasicLayout.less

promote trigger weight

---

src/components/AvatarList/index.d.ts
src/components/TagSelect/index.js

Fix bug when TagSelectOption is 1

---

src/components/AvatarList/index.d.ts
src/components/Charts/Bar/index.d.ts
src/components/Charts/ChartCard/index.d.ts
src/components/Charts/Field/index.d.ts
src/components/Charts/Gauge/index.d.ts
src/components/Charts/MiniArea/index.d.ts
src/components/Charts/MiniBar/index.d.ts
src/components/Charts/MiniProgress/index.d.ts
src/components/Charts/Pie/index.d.ts
src/components/Charts/Radar/index.d.ts
src/components/Charts/TagCloud/index.d.ts
src/components/Charts/TimelineChart/index.d.ts
src/components/Charts/WaterWave/index.d.ts
src/components/CountDown/index.d.ts
src/components/DescriptionList/index.d.ts
src/components/Ellipsis/index.d.ts
src/components/Exception/index.d.ts
src/components/FooterToolbar/index.d.ts
src/components/GlobalFooter/index.d.ts
src/components/HeaderSearch/index.d.ts
src/components/NoticeIcon/index.d.ts
src/components/NumberInfo/index.d.ts
src/components/NumberInfo/index.md
src/components/PageHeader/index.d.ts
src/components/Result/index.d.ts
src/components/TagSelect/index.d.ts
src/components/Trend/index.d.ts

d.ts文件已经全部完成了. 我测试了我用过的组件.
还有一个问题  是否需要全部支持 style props?

Support typescript 

---

src/components/NoticeIcon/index.js

修复元素 Children 数量只有一个的时候 map报错的问题.

fix component Children map error

---

src/routes/Dashboard/Analysis.js
src/routes/Dashboard/Workplace.less

Reformatted

---

src/routes/Forms/BasicForm.js
src/routes/List/TableList.js

Repair query form parameters not reset problem

---

src/components/Charts/index.js
src/index.js

https://github.com/babel/babel/issues/2212

No default with export multi objects

---

src/models/list.js
src/routes/List/SearchList.js

Unlimited list to add a special method

---

src/utils/request.js

增加了详细的提示.
修改 了 DELETE 和 204返回空对象的处理.
401 和 403 也许应该重定向.

Add clearer tips

---

src/common/menu.js
src/layouts/BasicLayout.js
src/routes/List/List.js

fix list redirect bug

---

src/components/SiderMenu/SiderMenu.js

fix warning: Failed prop type: Invalid prop `onClick` of type `boolean` supplied to `Link`, expected `function`

Fix warning of applying `bool` into onClick prop

---

src/components/Authorized/CheckPermissions.test.js
src/components/Authorized/index.d.ts

Authorized add typescript support.
For #93

Authorized typescript

---

src/layouts/UserLayout.js

/user is just empty layout page
maybe it should be possible to configure in common/router.js
```
'/user': {
component: dynamicWrapper(app, [], () => import('../layouts/UserLayout')),
redirect: '/user/login'
},
```
let me know what you think.

redirect from /user to /user/login

---

src/router.js

Use redux connected router

---

package.json
src/index.js
src/models/login.js

 Increase url-polyfill, ie11 edge support

---

src/components/Login/index.js
src/components/Login/index.less
src/index.less
src/layouts/BasicLayout.js
src/layouts/UserLayout.js
src/layouts/UserLayout.less

- move background gets displayed below login/registration form  on 4k monitor. this fix aligns the background with the top of the container.
- Improve mobile styles and simplify width management in  login and register (UserLayout)

move background on login page to correct position on large screens

---

.gitignore
package.json
src/common/router.js
src/components/PageHeader/index.js
src/components/SiderMenu/SiderMenu.js
src/utils/utils.js

带参数得路由现在可以和meun 匹配了
`/user/:id` === `/user`
将 PageHeader生成面包屑的逻辑做了拆分.原来太秀了不好懂

fix parameters match warning

---

src/components/TagSelect/index.d.ts
src/components/TagSelect/index.js
src/components/TagSelect/index.md

#761 
主要实现
- 通过`value`控制TagSelect选中项
- 支持`number`类型value

修改TagSelect为受控组件

---

src/components/Authorized/CheckPermissions.js
src/components/Authorized/index.d.ts
src/components/Authorized/index.md
src/models/login.js
src/router.js
src/utils/Authorized.js

注入authority。修改了文档
具体看 #692 ，不推荐使用数组作为参数

authority injection

---

src/components/GlobalHeader/index.less

use 100vh instead of 100%

---

src/components/PageHeader/index.d.ts
src/components/PageHeader/index.js

Allow `PageHeader` and `PageHeaderLayout` to set `Tab` extraContent.

Add PageHeader new props `tabBarExtraContent` to be pass to `Tabs`

---

src/routes/List/Articles.js
src/routes/List/BasicList.js

It should format time as 24 hour instead of 12 hour.

fix moment format

---

package.json

https://github.com/alibaba/BizCharts/commit/9a9471db29234b25a6d85eff3447af453126d1ee

更新bizcharts版本，解决不兼容ie9/ie10问题

---

src/routes/Forms/TableForm.js

It  saves  the  input content  when  lost  focus.  So,  There is no opportunity  for ‘button of save’ & ‘button of cancel’  to be used.

Let ‘button of save’ & ‘button of cancel’ have a opportunity  to be used -- Advanced Form

---

mock/rule.js
src/models/rule.js
src/routes/List/TableList.js
src/services/api.js

New page - step modal

---

src/utils/request.js

According to these issues (#149 #260 #535), some users talk about the problem on request.js when handling FormData, thus I make a minor change on request.js to provide this ability. I think this change should cover most of the cases that need FormData.

let request.js be able to deal with FormData

---

src/components/Charts/Radar/index.js
src/components/StandardTable/index.js
src/layouts/BasicLayout.js
src/layouts/UserLayout.js
src/routes/Dashboard/Analysis.js
src/routes/Dashboard/Monitor.js
src/routes/Forms/StepForm/Step1.js
src/routes/Forms/StepForm/Step3.js
src/routes/Forms/StepForm/index.js
src/routes/Forms/TableForm.js
src/routes/List/Articles.js
src/routes/Profile/AdvancedProfile.js
src/routes/Result/Error.js
src/routes/Result/Success.js

div to fragment

---

src/common/menu.js
src/components/PageHeader/index.js
src/components/PageHeader/index.test.js
src/components/SiderMenu/SiderMenu.js
src/components/SiderMenu/SilderMenu.test.js
src/components/utils/pathTools.js
src/components/utils/pathTools.test.js

- 增加了 一部分 meun 测试
- 修复了一些 bug 完美修复了 #821
- 抽取了一些公共方法
-  meun data  dashboard/analysis -> /dashboard/analysis
cc @WhatAKitty

add meun test and Modify part of the logic

---

src/components/Login/demo/basic.md
src/components/Login/index.en-US.md
src/components/Login/index.md
src/components/Login/index.zh-CN.md
src/components/Login/map.js

#120 Translated the document of the Login component.

Translated the document of the Login component.

---

src/layouts/LoadingPage.js

LoadingPage

---

src/components/PageHeader/index.js

这一步应该判断没指定默认tab时候，tab默认为tablist第一个.

pageHeader组件Tablist

---

src/models/error.js
src/routes/Exception/triggerException.js
src/services/error.js

fix: https://github.com/ant-design/ant-design-pro/issues/976

Remove Error Trigger dump code & support static env

---

src/components/Charts/ChartCard/index.d.ts
src/components/Charts/ChartCard/index.js
src/components/Charts/Pie/index.d.ts
src/components/Charts/Pie/index.js
src/components/Charts/demo/chart-card.md
src/components/Charts/demo/mix.md
src/components/Charts/demo/pie.md
src/components/Charts/index.md
src/routes/Dashboard/Analysis.js

break change:
```diff
- <Pie total={yuan(1000)} /> => &yen;1000
+ <Pie total={()=><span dangerouslySetInnerHTML={{ __html: yuan(1000) }} /> => ¥1000
- <ChartCard total={yuan(1000)} /> => &yen;1000
+ <ChartCard total={()=><span dangerouslySetInnerHTML={{ __html: yuan(1000) }} /> => ¥1000
```

Fixed: #1142

---

src/components/StandardTable/index.js

StandardTable need a "rowKey" prop

---

src/components/HeaderSearch/index.js
src/components/HeaderSearch/index.md

[#1136](https://github.com/ant-design/ant-design-pro/issues/1136)

顶部搜索框组件添加默认打开配置

---

package.json
src/components/Charts/TagCloud/index.js
src/components/FooterToolbar/demo/basic.md
src/components/HeaderSearch/index.js
src/components/HeaderSearch/index.md
src/components/Login/LoginItem.js
src/components/Login/LoginTab.js
src/components/Login/index.js
src/components/Login/loginContext.js
src/components/Login/map.js
src/routes/List/TableList.js

chang to new context api

---

src/utils/request.js

remove setting Content-Type when body is FormData

---

src/components/Charts/Radar/index.js

componentDidMount() {
requestAnimationFrame(() => {
this.getLengendData();
});
}

getLengendData()->getLegendData()

---

src/components/NoticeIcon/NoticeIconTab.d.ts
src/components/NoticeIcon/NoticeList.js
src/components/NoticeIcon/index.en-US.md
src/components/NoticeIcon/index.zh-CN.md

add new props 
look in https://github.com/ant-design/ant-design-pro/issues/366

NoticeIcon add hideClear props

---

src/components/Login/index.less

fix issue #1425 
explain message block display error

fix issue #1425

---

src/components/Ellipsis/index.js

fixed: https://github.com/ant-design/ant-design-pro/issues/1557

Fix length property include "..." tail length #1557

---

src/routes/User/Login.js

Use `submitting` from `props`.

Use submitting from props

---

src/utils/utils.js

Signed-off-by: jiangjiahao <1173860556@qq.com>

修复digitUppercase(2.01)返回为贰元整的，数字大写增加了“万亿”

---

src/components/Login/index.less

revert #1448 remove captcha button height

---

src/layouts/Header.less

fix fixed header transition

---

src/components/DescriptionList/Description.js

Fix children empty judgement in Description

---

src/components/Charts/Radar/index.js

[#1660](https://github.com/ant-design/ant-design-pro/issues/1660)

fix error in workplace #1660

---

src/components/Ellipsis/index.js

fixed https://github.com/ant-design/ant-design-pro/issues/1258

Fix Ellipsis floor-mid to ceil-mid #1258

---

src/components/SettingDarwer/index.js

autoHideHeader 的选项应该在 fixedHeader 开启时显示

fix: judgment condition of autoHideHeader switch

---

src/components/GlobalHeader/index.js

For robustness

---

src/components/GlobalHeader/index.js

"currentUser" is a read-only variable

stop re-assigning read-only "currentUser"

---

src/components/NoticeIcon/index.js

onTabChange fixed

---

package.json

See https://nodesecurity.io/advisories/532

Bump moment version to handle dependency security

---

src/layouts/BasicLayout.js

```js
'screen-xl': {
minWidth: 1200,
maxWidth: 1599,
},
'screen-xxl': {
minWidth: 1600,
},
```

add screen-xxl

---

src/layouts/UserLayout.js
src/models/login.js
src/router.js
src/utils/utils.js

Redirect to expected page after logging in.

---

.gitignore
.webpackrc.js
scripts/AddlocalIdentName.js
scripts/getLocalIdentName.js
scripts/mergeLessPlugin.js
scripts/replacedefaultLess.js
webpack.config.js

这个办法虽然已经提取了所有的 less变量，但是由于 css-module 的原因。提取出来的 class 并不正确。
可能需要我单独写一个post-css 插件了。
或许有别的更好的办法。
@afc163  @sorrycc @yesmeck @nikogu

[WIP]  difficulty:Fix the bug that switching themes is incomplete

---

src/utils/authority.js

localStorage  array

---

config/config.js
package.json
src/pages/document.ejs

WIP: Migrate to umi 2 beta

---

config/config.js
package.json
src/pages/document.ejs

Reverts ant-design/ant-design-pro#1878

Revert "WIP: Migrate to umi 2 beta"

---

jest.config.js

test: fix tests by adding testURL to jest configuration

---

src/components/Ellipsis/index.js

fixed: https://github.com/ant-design/ant-design-pro/issues/1882

fix Ellipsis break in firefox #1882

---

src/components/HeaderSearch/index.js

在之前的[修复lint error的commit](https://github.com/ant-design/ant-design-pro/commit/d1b424df1cbdd77fdc58f402d9f32b4771eb29f7#diff-1abfc0b64e4d74235a43e5e703f61615R76)中代码放错地方了

Fix header search debounce enter

---

src/components/HeaderSearch/index.js

Add param to onChange event

---

src/common/router.js

menu key对switch的子路由页面没有配置menu时取父菜单配置

---

src/layouts/BasicLayout.js

`for key in array`：key 是 array 的 index；
`for key of array`：key 是 array 的 value。
所以这里要么用`for const key in routerData`，要么用`for const key of Object.keys(routerData)`

fix for in loop.

---

src/pages/Forms/AdvancedForm.js

fixed form

---

src/components/GlobalHeader/index.js
src/components/SiderMenu/BaseMenu.js
src/components/SiderMenu/SiderMenu.js
src/components/SiderMenu/SliderMenu.js
src/components/TopNavHeader/index.js
src/layouts/Header.js
src/layouts/PageHeaderLayout.js
src/layouts/UserLayout.js
src/pages/404.js
src/pages/Account/Center/Center.js
src/pages/Account/Settings/Info.js
src/pages/Dashboard/Workplace.js
src/pages/Exception/403.js
src/pages/Exception/404.js
src/pages/Exception/500.js
src/pages/Forms/StepForm/Step1.js
src/pages/Forms/StepForm/Step2.js
src/pages/Forms/StepForm/Step3.js
src/pages/List/List.js
src/pages/User/Login.js
src/pages/User/Register.js
src/pages/User/RegisterResult.js

- 去掉 routerRedux
- 去掉 dva/router
- 使用 umi/link，umi/router

fixed umi/link umi/router

---

config/router.config.js
package.json
src/pages/Authorized.js
src/pages/Dashboard/Monitor.js

Fix authorized route

---

config/router.config.js
package.json
src/components/GlobalHeader/index.js
src/components/GlobalHeader/index.less
src/components/TopNavHeader/index.js
src/components/TopNavHeader/index.less
src/layouts/BasicLayout.js
src/pages/404.js

handcode and use Automatically closed menu

---

src/components/GlobalHeader/index.less

trigger button 68px
GlobalHeader 64px
decrease trigger padding

trigger button overflow

---

src/layouts/BasicLayout.js

remove getBashRedirect

---

src/layouts/BasicLayout.js

fix #2175  the Siderbar padding error on the mobile mode with fixSiderbar=true

 fix the Siderbar padding error on the mobile mode with fixSiderbar=true

---

package.json
src/pages/document.ejs

0.9.4 版本的 data-set 有 bug，会导致渲染卡顿。
https://yuque.antfin-inc.com/antv/topics/44#reply-192085

fix: update data-set to new version and use new cdn url

---

src/components/Charts/MiniArea/index.d.ts

实测, 字符串应该没有问题. 
参考 https://github.com/alibaba/BizCharts/blob/74e8bcfd18aa936abdbb6af9fc591f45b3a1f2c2/doc/tutorial/data.md 的例子也说没问题.

Update Charts/MiniArea props type

---

src/components/Ellipsis/index.js

fix #2335 fix tooltip position of Ellipsis

---

src/components/Login/LoginItem.js

`WarpFormItem` should be `WrapFormItem`

wrong spelling error

---

src/components/Ellipsis/index.js

debug info
```js
TypeError: text is undefined
```

fix: compatible with Firefox 40.0.3

---

src/pages/Dashboard/Analysis.js

Update Analysis.js, remove unused code.

---

src/pages/Result/Success.js

Step's description for Success Page has incorrect style.
Add ``` textAlign: 'left'``` for desc2.

Fix desc style for Success Page

---

src/components/SelectLang/index.js

```getLocale``` is a function rather than an object.
Should change `getLocale` to `getLocale()`

fix selectedKeys error of SelectLang

---

.dockerignore
Dockerfile
Dockerfile.dev
README.md
README.zh-CN.md
docker/docker-compose.dev.yml
docker/docker-compose.yml
docker/nginx.conf
package.json

@ja573  made some changes
move `Dockerfile` and `Dockerfile.dev` to `/`
move test:all to package.json

add docker support

---

src/locales/en-US.js
src/locales/pt-BR.js
src/locales/zh-CN.js
src/locales/zh-TW.js
src/pages/User/Login.js

登录错误提示加入国际化

---

src/components/GlobalFooter/index.js
src/e2e/layout.e2e.js

add layout test

---

src/pages/User/Login.js

login 账号密码错误的时候  报错信息不对

---

src/components/Authorized/CheckPermissions.js

fix: #2508，string type not equal will still pass

---

src/components/HeaderSearch/index.d.ts

:bug: 修复HeaderSearch中defaultOpen、open参数指定问题

---

src/pages/User/Register.js

fix: registration password field floating popover 

---

src/pages/User/Register.js

The register page requires 11 digits

---

package.json

fix ant-design#2407

---

src/layouts/Header.js

fix slide  hidden Header bug

---

src/components/Charts/Gauge/index.js

解决图表Gauge中值显示的浮点数bug

---

src/components/Login/LoginItem.js
src/components/Login/index.less
src/layouts/UserLayout.less
src/locales/en-US.js
src/locales/pt-BR.js
src/locales/zh-CN.js
src/locales/zh-TW.js

Signed-off-by: PangZhiGang <306888588@qq.com>

增加验证码按钮国际化， Fix #2790 .

---

src/components/NoticeIcon/index.zh-CN.md

[NoticeIcon] Update index.zh-CN.md 

---

src/components/Charts/Gauge/index.js

Guade组件指针指向不准的问题

---

src/models/login.js

fix bug by logout cause path exception

---

src/components/ActiveChart/index.js
src/components/ActiveChart/index.less

Before:
After:
Design in [sketch](https://ant.design/docs/spec/download):

Add dashed line to ActiveChart as it was design in sketch

---

.dockerignore
Dockerfile.hub
README.md
README.zh-CN.md
package.json

Preview the Ant Design Pro in a faster way
```bash
$ docker pull chenshuai2144/ant-design-pro
$ docker run -p 80:80 chenshuai2144/ant-design-pro
```

add preview use docker

---

src/components/PageHeaderWrapper/index.js

fix #2558, breadcrumbList doesn't work in PageHeaderWrapper

---

src/components/Charts/Radar/index.js
src/components/Charts/TagCloud/index.js
src/components/Charts/TagCloud/index.less

solve the problem mentioned in issue #2881

change the default tickCount of Radar

---

package.json

Fix https://github.com/ant-design/ant-design-pro/issues/2971

Update React to 16.6.3

---

src/utils/utils.js

 调整utils.js里面formatWan方法的返回值

---

src/components/GlobalHeader/index.less

change `width` to `min-width` in order to be compatible with the width of the globalheader's account is more than 160px

fix: hover effect

---

src/components/GlobalHeader/index.js
src/components/GlobalHeader/index.less
src/components/SelectLang/index.js
src/components/SelectLang/index.less
src/components/SiderMenu/BaseMenu.js
src/components/SiderMenu/index.less
src/components/TopNavHeader/index.js
src/components/TopNavHeader/index.less
src/layouts/BasicLayout.js
src/layouts/BasicLayout.less

Changing `@layout-header-height` before:
Now:

Layout header height correctly change when `@layout-header-height` change.

---

src/pages/List/TableList.js

fix #2965 查询表格关闭配置Modal时没有渐隐效果

---

src/locales/zh-CN/settings.js
src/locales/zh-TW/settings.js

:bug: fix locale error Close:#3048

---

src/layouts/BasicLayout.js
src/models/menu.js

:bug: fix route noAuthority nowork Close: #2998

---

scripts/prettier.js

added less files and config files to the prettier script

---

src/components/GlobalHeader/index.less

Reverts ant-design/ant-design-pro#3173
Fixed by https://github.com/ant-design/ant-design/commit/3aeca7c10ec6ee3441f024fe7fdb5ae9e00564dd#diff-b2f38984ba341f88478e5e27afb4404c

Revert "Set GlobalHeader padding"

---

src/components/SiderMenu/index.less

修复在手机端预览时，侧边菜单样式问题。

---

src/components/HeaderSearch/index.en-US.md
src/components/HeaderSearch/index.zh-CN.md

修改onChange、onSearch中英文 文档说明
添加onSelect文档说明

修改HeaderSearch组件的中英文文档说明

---

src/components/HeaderSearch/index.js

prettier HeaderSearch

---

src/defaultSettings.js
src/layouts/BasicLayout.js

Title is a string and defaults to Ant Design Pro.

feat: add new config "title"

---

README.md
functions/index.js
functions/matchMock.js
functions/package.json
package.json

fix https://github.com/ant-design/ant-design-pro/issues/3307

use a new docker mirror address

---

src/layouts/BasicLayout.js

forEach is more semantics reasonable and performance friendly(even it doesn't matter in this place).

forEach should be used instead of map

---

config/config.js
package.json

左边是加之前，右边是加之后。gzip 后加起来少 10K 左右。

feat: enable tree-shaking

---

.gitpod.yml
README.md

This PR lowers the barrier for contributers and generally allows tinkering with the code base easily using Gitpod, a free dev environment service for GitHub. I configured it so it runs 
- `npm install` followed by 
- `npm start` which will automatically open the web app in the preview. 
The button in the readme allows anyone to immediately play around with the code and try out changes. Forking, committing and creating a PR is integrated as well.
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/4fe0c4b9-7e8b-4ad5-a86d-9efe31f81a7b)

Simplify getting started

---

config/config.js

feat: disable hardSource

---

src/components/Charts/TimelineChart/index.js

fix TimelineChart: deal with non-array data

---

src/pages/Dashboard/Analysis.js
src/pages/Dashboard/Analysis.less
src/pages/Dashboard/ProportionSales.js

Fix #3312 
> 话说 Pro 不是只支持 IE11+ 嘛，为啥不让直接用 `<Row type="flex">` 🤪

fix: different card heights in Analysis

---

mock/rule.js
src/pages/List/TableList.js
src/services/api.js

enhance TableList: auto search after editing

---

src/app.js

fix: error-processing-request
Close: #3398

fix: error-processing-request

---

package.json
src/defaultSettings.js
src/layouts/BasicLayout.js
src/models/menu.js

The default value of menu.enableLocale is false.
If true, the menu and title internationalization will be turned off.

feat: add new config "menu.enableLocale"

---

jest-puppeteer.config.js
tests/run-tests.js

try fix test error

---

src/global.less
src/pages/List/TableList.js

fix https://github.com/ant-design/ant-design-pro/issues/1755

add responsive-table

---

src/components/SiderMenu/SiderMenu.js
src/components/SiderMenu/index.less
src/layouts/BasicLayout.js
src/layouts/Header.js
src/layouts/UserLayout.js

look here   https://github.com/ant-design/ant-design-pro/issues/3294

remove PureComponent

---

jest-puppeteer.config.js
package.json

- Upgrade jest-puppeteer@3.9.0, The new version fixes some bugs. see https://github.com/smooth-code/jest-puppeteer/blob/master/CHANGELOG.md
- Remove part of puppeteer config because jest-puppeteer already exists in the default configuration. see https://github.com/smooth-code/jest-puppeteer/blob/40bc3a24edf0a0b2a862709c821cc61483062258/packages/jest-environment-puppeteer/src/readConfig.js#L17

chore: upgrade jest-puppeteer and remove some puppeteer config

---

azure-pipelines.yml
src/components/SiderMenu/SiderMenu.js

style: prettier SiderMenu.js

---

src/layouts/BasicLayout.js

Thank @rayronvictor
Close: #3072

Route authority attribute behavior

---

azure-pipelines.yml
config/router.config.js
mock/profile.js
src/pages/List/TableList.js
src/pages/Profile/BasicProfile.js
src/pages/Profile/models/profile.js
src/services/api.js

add a demo for from list to details

feat: add a demo that jump to details

---

README.md
README.ru-RU.md
README.zh-CN.md

doc: add umi-badge

---

config/config.js
src/pages/document.ejs

feat: Officially traded will use cdn to optimize bizchart

---

src/components/IconFont/index.js
src/components/SiderMenu/BaseMenu.js
src/defaultSettings.js

- 新增IconFont组件
- 菜单可以添加自己IconFont的项目图标。
菜单使用个人IconFont图标示例如下图：

增加IconFont组件、菜单图标可以使用自己的IconFont项目图标

---

config/router.config.js
src/layouts/BasicLayout.js
src/layouts/UserLayout.js
src/locales/en-US/menu.js
src/locales/pt-BR/menu.js
src/locales/zh-CN/menu.js
src/locales/zh-TW/menu.js
src/pages/User/Login.less
src/pages/User/Register.less
src/utils/getPageTitle.js

Login title

---

src/pages/List/Articles.js

when select 3 item ，text branch

---

src/components/PageHeader/index.js

fix PageHeader no title bug

---

src/layouts/BlankLayout.js

fix: React does not recognize the `staticContext` prop on a DOM element.

---

src/components/SettingDrawer/index.js

Remove drawer onHandleClick

---

src/components/Charts/TagCloud/index.js

fix: TagCloud style override bug

---

package.json
src/components/Login/index.d.ts
src/pages/Profile/AdvancedProfile.tsx
src/pages/User/Login.tsx
src/typings.d.ts

fix type definition of `Login` instance

[V3] [Page] User/Login

---

src/components/Authorized/demo/secured.md

render 方法里面 需要有return

---

package.json
src/components/Authorized/AuthorizedRoute.js

fix: Consumer error with react-router-dom@4.4

---

src/components/Authorized/CheckPermissions.tsx
src/components/Authorized/PromiseRender.tsx
src/components/Authorized/Secured.tsx

https://github.com/ant-design/ant-design-pro/pull/3616#issuecomment-475300384

[v3] [Authorized] fix props cannot be delivered if target is a react element

---

config/router.config.js
src/layouts/BasicLayout.js
src/models/menu.js
src/pages/Authorized.js
src/utils/authority.js

Close: #3692 
看看要不要修改这个逻辑，感觉现在需要登录之后再查看页面，对pro用户来说应该是可以接收的。

Cancel default permissions

---

package.json
src/components/PageHeader/index.d.ts

补全PageHeader缺少的属性定义[https://github.com/ant-design/ant-design-pro/issues/3661](url)

fix:补全PageHeader组件d.ts定义

---

README.md
README.ru-RU.md
README.tr-TR.md
README.zh-CN.md

I translated the read me page to Turkish

Turkish language

---

src/components/Authorized/CheckPermissions.js
src/components/Authorized/PromiseRender.js
src/components/Authorized/Secured.js

close https://github.com/ant-design/ant-design-pro/pull/3616#issuecomment-475300384

[Authorized] fix props cannot be delivered if target is a react element

---

src/locales/zh-CN/exception.js
src/locales/zh-TW/exception.js

change exception

---

src/models/login.js

redirect of different origins will be ignored

---

src/pages/Authorized.js

fix: hasLogin redirect to login page

---

src/models/login.js

Repeated addition search

---

config/router.config.js
src/app.js

close page permission control

---

config/router.config.js
src/app.js

Reverts ant-design/ant-design-pro#3842

Revert "close page permission control"

---

package.json
src/components/GlobalHeader/RightContent.tsx
src/components/SiderMenu/BaseMenu.tsx
src/components/SiderMenu/SiderMenu.tsx
src/components/SiderMenu/SiderMenuUtils.ts
src/components/SiderMenu/index.tsx
src/layouts/BasicLayout.tsx
src/layouts/Footer.tsx
src/layouts/Header.tsx
src/layouts/UserLayout.tsx
src/models/connect.d.ts
src/models/global.ts
src/models/menu.ts
src/pages/Authorized.tsx
src/typings.d.ts

- location, history, match 等定义改为从 umi 引入继承
- 更新部分依赖的版本
- 一些其他的类型定义优化

[v4] fix type definition

---

package.json
src/services/api.js
src/utils/request.js

使用 umi-request 来替换 fetch。减少代码量。删除了 cachesave 这个 hack 的逻辑

use umi-request

---

src/locales/en-US/login.js
src/locales/pt-BR/login.js
src/locales/zh-CN/login.js
src/locales/zh-TW/login.js
src/pages/User/Login.js
src/pages/User/Register.js

Add a message hint to prevent users from treating it as a real project

feat: add login message

---

package.json

upgrade antd for using page-header

---

README.ja-JP.md
README.md
README.tr-TR.md
README.zh-CN.md

Hello, I'm Japanese contributor for this project.
I wanted Japanese README but, there was no.
Because, I made it.
If you don't allow , please close this pull request.
---
If this pull request is permitted and merged, The below issue will be closed automatically. 
Close https://github.com/ant-design/ant-design-pro/issues/3930

ja-JP README

---

mock/route.js
src/app.js

remove serve authRoutes

---

lambda/mock/matchMock.js
netlify.toml

use netlify functions

---

src/components/PageHeaderWrapper/breadcrumb.js

当hideInBreadcrumb==true,面包屑会报错

Fix当hideInBreadcrumb==true,面包屑报错的问题

---

src/components/PageHeaderWrapper/index.js

PageHeaderWrapper组件内PageHeader部分显示判断修改为title存在即可

PageHeaderWrapper组件bug

---

src/components/Authorized/CheckPermissions.js
src/components/Authorized/PromiseRender.js
src/components/Authorized/Secured.js
src/components/PageHeaderWrapper/breadcrumb.js
src/components/PageHeaderWrapper/index.js

提供一个和以前一样直接隐藏 hiddenBreadcrumb 的props，
Breadcrumb在不使用多语言时，也会报错误（与menu共用了同一个控制逻辑）。

hiddenBreadcrumb && menu.disableLocal

---

src/components/Charts/Pie/index.js
src/utils/utils.js

remove useless code.
Fixes #4011

remove useless code

---

src/components/SiderMenu/BaseMenu.js

bugfix:fix #3878, In the top mode. Menu will follow the slide

---

src/pages/Dashboard/Analysis.less

Rm hack ie9

---

src/layouts/Footer.js
src/layouts/UserLayout.js

change the copyright time

---

src/defaultSettings.js
src/global.js

用 pwa 很容易,但是用好它很难.
https://jakearchibald.com/2014/offline-cookbook/#cache-then-network
aslo fix https://github.com/ant-design/ant-design-pro/issues/4083

rm pwa in site

---

src/components/PageHeaderWrapper/index.less

https://github.com/ant-design/ant-design-pro/blob/b86048b4db8d5c17241e08b29a2226f6318529a5/src/components/PageHeaderWrapper/index.less#L1-L11
rename .content to .children-content

fix #4079 PageHeaderWrapper margin in xs screen

---

src/pages/Account/Settings/Info.js

Optimizes animation by doing the following changes:
- Moves offsetWidth, innerWidth like expensive calculations out of requestAnimationFrame
- Adds menu mode change control before requesting the animation frame

requestAnimationFrame optimization

---

package.json

**set engines>=10.0.0 to use Promise.finally() method in the .\scripts\lint-prettier.js:44**
```bash
$ git commit -m "test: lint"
husky > pre-commit (node v8.12.0)
> ant-design-pro@2.3.1 lint-staged F:\antdproclient
> lint-staged
Stashing changes... [started]
Stashing changes... [skipped]
→ No partially staged files found...
Running linters... [started]
Running tasks for **/*.less [started]
Running tasks for **/*.{js,jsx} [started]
Running tasks for **/*.{js,ts,tsx,json,jsx,less} [started]
Running tasks for **/*.less [skipped]
→ No staged files match **/*.less
npm run lint-staged:js [started]
node ./scripts/lint-prettier.js [started]
node ./scripts/lint-prettier.js [failed]
→
Running tasks for **/*.{js,ts,tsx,json,jsx,less} [failed]
→
npm run lint-staged:js [completed]
Running tasks for …
```

fix: set engines>=10.0.0 to use Promise.finally() method

---

src/pages/List/List.js

fix(List): width of search input overflow in mobile mode

---

Dockerfile.dev
config/router.config.js
package.json
src/components/Charts/Bar/index.js
src/components/Charts/Pie/index.js
src/components/Charts/TagCloud/index.js
src/pages/Dashboard/Analysis.js
src/pages/Dashboard/Workplace.js
src/pages/List/TableList.js

修复以下几个问题：
先提到 v2 master，后面还需要提到 pro-blocks、pro-components 和 pro-layout 里去。

Fix warnings and details

---

README.fr-FR.md
README.ja-JP.md
README.md
README.ru-RU.md
README.tr-TR.md
README.zh-CN.md

您好，
我将README指令翻译成法语。
翻译完文件（英文）后，我会用法语翻译。
如果我需要改变一些事情，请告诉我。
-----
[View rendered README.fr-FR.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.fr-FR.md)
[View rendered README.ja-JP.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.ja-JP.md)
[View rendered README.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.md)
[View rendered README.ru-RU.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.ru-RU.md)
[View rendered README.tr-TR.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.tr-TR.md)
[View rendered README.zh-CN.md](https://github.com/loicpirez/ant-design-pro/blob/translation-fr-FR/README.zh-CN.md)

用法语翻译README

---

src/layouts/BasicLayout.tsx

chore: Add Layout comment

---

create-umi/README.md
create-umi/package.json
package.json

配置 `create-umi.copy` 项，用于替换对应的文件。目前有：
* README.md
* package.json
-----
[View rendered create-umi/README.md](https://github.com/ant-design/ant-design-pro/blob/add-copy/create-umi/README.md)

chore: Add copy files

---

README.fr-FR.md
README.ja-JP.md
README.md
README.ru-RU.md
README.tr-TR.md
README.zh-CN.md

卖身求免费
-----
[View rendered README.fr-FR.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.fr-FR.md)
[View rendered README.ja-JP.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.ja-JP.md)
[View rendered README.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.md)
[View rendered README.ru-RU.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.ru-RU.md)
[View rendered README.tr-TR.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.tr-TR.md)
[View rendered README.zh-CN.md](https://github.com/ant-design/ant-design-pro/blob/add-netlify/README.zh-CN.md)

add netlify  logo

---

src/components/CopyBlock/index.tsx
src/typings.d.ts

add block  a analytics to ga

---

scripts/fetch-blocks.js
src/models/connect.d.ts

修复类型参数传递的问题

---

scripts/fetch-blocks.js
src/components/CopyBlock/index.tsx

remove extra space

---

config/config.ts
scripts/fetch-blocks.js
src/components/GlobalHeader/RightContent.tsx
src/components/NoticeIcon/NoticeList.tsx
src/components/NoticeIcon/index.tsx
src/models/global.ts
src/pages/404.tsx

feat : fix #4565, add 404 page

---

package.json
src/pages/404.tsx

use antd Result

---

package.json
src/layouts/BasicLayout.tsx

如果是 url 不再需要将其放到 Link 中
close #4607

add isUrl judge

---

src/components/PageLoading/index.tsx

Component name should be PageLoading, not PageLoding

Fix component name

---

package.json

cli创建的项目内报错：缺少ts声明文件

---

src/utils/request.ts

解决客户端网络异常（如wifi断线）时，网络请求后无法触发notification.error的问题 #5096

解决客户端网络异常（如wifi断线）时，网络请求后无法触发notification.error的问题 #5096

---

src/components/Charts/WaterWave/index.js

记录了水波动画的位置，每次组件的percent更新后，水波动画可以从前一次位置升/降至新的位置；
而不是每次都从0开始涨；

解决水波图在初始动画的过程中，percent变化后导致水波图变成了正方形的问题；

---

config/config.ts

fix bug comments

---

src/components/SelectLang/index.tsx

The language is `en-US` but the flag is `en-UK`

Replace UK flag with US flag

---

config/defaultSettings.ts

fix: :bug: import { MenuTheme } path error in defaultSettings

---

src/services/login.ts

登录接口 request 引入问题导致统一的 errorHandler 无效

fix: Invalid request error handler in login page

---

config/plugin.config.ts
src/components/SettingDrawer/themeColorClient.ts

替换`24,144,255`这样的主题色，解决外框主题色不一致问题：

替换`24,144,255`这样的主题色

---

package.json

使用 cross-env 适配windows端 
close #5375

fix(package.json): npm run format-imports adapt windows

---

README.pt-BR.md

-----
[View rendered README.pt-BR.md](https://github.com/robsonsilv4/ant-design-pro/blob/patch-1/README.pt-BR.md)

Added README in portuguese (pt-BR)

---

src/utils/authority.ts

bugfix: auto reload Authorized

---

README.md

-----
[View rendered README.md](https://github.com/robsonsilv4/ant-design-pro/blob/patch-2/README.md)

update README languages ref

---

package.json

allow dev start without no UMI_UI
增加一个npm script 以便有时候dev启动时不想使用umi ui，

allow dev start without no UMI_UI

---

config/config.ts
src/components/Authorized/Authorized.tsx
src/layouts/BasicLayout.tsx
src/locales/en-US/menu.ts
src/locales/pt-BR/menu.ts
src/locales/zh-CN/menu.ts
src/locales/zh-TW/menu.ts
src/pages/Admin.tsx
src/utils/utils.ts

增加一个 如何使用路由权限的 demo
ref https://github.com/ant-design/ant-design-pro/issues/5348
ref https://github.com/ant-design/ant-design-pro/issues/5451

Feat: Add authorized router demo

---

src/models/connect.d.ts

更新 dispatch 类型定义，支持 dispatch 返回 promise 的形式：
```ts
dispatch<Promise<boolean>>({
type: '',
}).then((status: boolean) => {
});
```

update dispatch type

---

README.tr-TR.md

Turkish readme file update from 2.0 to 4.0
-----
[View rendered README.tr-TR.md](https://github.com/codesignist/ant-design-pro/blob/patch-3/README.tr-TR.md)

Turkish ReadMe Update

---

src/components/GlobalHeader/index.less

same as https://github.com/ant-design/ant-design-pro-layout/pull/183

remove unused less code

---

tsconfig.json

add exclude

---

config/plugin.config.ts

fix: webpackChain config type fix

---

README.fr-FR.md
README.ja-JP.md
README.pt-BR.md
README.ru-RU.md
README.zh-CN.md

-----
[View rendered README.fr-FR.md](https://github.com/yunkii/ant-design-pro/blob/update-readme/README.fr-FR.md)
[View rendered README.ja-JP.md](https://github.com/yunkii/ant-design-pro/blob/update-readme/README.ja-JP.md)
[View rendered README.pt-BR.md](https://github.com/yunkii/ant-design-pro/blob/update-readme/README.pt-BR.md)
[View rendered README.ru-RU.md](https://github.com/yunkii/ant-design-pro/blob/update-readme/README.ru-RU.md)
[View rendered README.zh-CN.md](https://github.com/yunkii/ant-design-pro/blob/update-readme/README.zh-CN.md)

doc: update navigation

---

package.json

Reverts ant-design/ant-design-pro#5866
close #5876

Revert "Upgrade husky to version 4.0.0"

---

src/components/GlobalHeader/index.less

Issues: https://github.com/ant-design/ant-design-pro/issues/5903
修复菜单模式顶部菜单，主题是亮色时，右上角图标高度坍塌的问题

fix:bug header style

---

config/config.ts
src/utils/utils.ts

Hi
in route definitions
I noticed that the authorization of subroutes is not working.
I offer the solution for your evaluation.
good work.

fixes/Route Recursive Authority #5931

---

package.json
src/layouts/SecurityLayout.tsx
src/pages/404.tsx

bugfix: fix lint error

---

src/components/GlobalHeader/RightContent.tsx
src/layouts/SecurityLayout.tsx

bugfix: fix SecurityLayout error (ant-design#5640)

---

package.json

Reverts ant-design/ant-design-pro#6011

Revert "New version of antd (3.26.12) broke the build"

---

src/layouts/BasicLayout.tsx
src/service-worker.js

1. update i18n
2. fix regex for target domains

using i18n

---

package.json

emmmm
```
'import/no-extraneous-dependencies': [
2,
{
optionalDependencies: true,
devDependencies: [
'**/tests/**.{ts,js,jsx,tsx}',
'**/_test_/**.{ts,js,jsx,tsx}',
'/mock/**/**.{ts,js,jsx,tsx}',
'**/**.test.{ts,js,jsx,tsx}',
'**/_mock.{ts,js,jsx,tsx}',
'**/example/**.{ts,js,jsx,tsx}',
'**/examples/**.{ts,js,jsx,tsx}',
],
},
],
```

🤡 Mock: add express for mock lint

---

package.json
src/layouts/UserLayout.tsx

- 减少安装大小
- 解决 react-helmet 使用了过期 api 的问题

➖ dependency: Optimization dependencies

---

src/pages/ListTableList/components/UpdateForm.tsx
src/pages/ListTableList/index.tsx

close https://github.com/ant-design/ant-design-pro/issues/6192

💩 code: deleted a redundant line of code and changed a mistake at ListTableList

---

src/components/NoticeIcon/NoticeList.less
src/utils/utils.less

🔥 clean: remove  unused less

---

package.json

fix: 🐛 eslint missing

---

package.json

umi 现在类型需要动态生成，安装完依赖之后默认帮用户安装一下
------
The type of umi needs to be dynamically generated now. After installing the dependencies, another group of users will install it.

🏗: add script for post install

---

package.json

close https://github.com/ant-design/ant-design-pro/issues/6524
close https://github.com/ant-design/ant-design-pro/issues/6523
close https://github.com/ant-design/ant-design-pro/issues/6526
close https://github.com/ant-design/ant-design-pro/issues/6512

🚑 hotfix: fix delopy error

---

config/defaultSettings.ts
src/components/GlobalHeader/RightContent.tsx
src/global.tsx
src/models/connect.d.ts
src/pages/ListTableList/components/UpdateForm.tsx

close https://github.com/ant-design/ant-design-pro/pull/6473
close https://github.com/ant-design/ant-design-pro/pull/6418
close https://github.com/ant-design/ant-design-pro/pull/6447

🐛 bug: fix submit bug

---

config/defaultSettings.ts
package.json
src/app.tsx
src/utils/utils.test.ts

📌 versions: use alpha version

---

config/defaultSettings.ts
mock/user.ts
package.json
src/pages/user/login/components/Login/LoginItem.tsx
src/pages/user/login/components/Login/index.tsx
src/pages/user/login/components/Login/map.tsx
src/pages/user/login/index.tsx
src/services/login.ts

https://github.com/ant-design/ant-design-pro/issues/6686

userName to username

---

src/pages/user/login/index.tsx

correct the text

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
azure-pipelines.yml
src/layouts/BasicLayout.tsx

close https://github.com/ant-design/ant-design/issues/24725
close https://github.com/ant-design/ant-design-pro/issues/6759
close https://github.com/ant-design/ant-design-pro-layout/issues/490
close https://github.com/ant-design/ant-design-pro-layout/issues/489
close https://github.com/ant-design/ant-design-pro/issues/6761

🔥 clean: remove unuse code

---

config/defaultSettings.ts
package.json
src/components/GlobalHeader/RightContent.tsx
src/layouts/BasicLayout.tsx

📌 versions: up pro-layout to 6.x

---

src/app.tsx

fix infinite loop of login page

---

config/config.ts

🐛 bug: fix the position of comment baseNavigator (#7157)

---

README.ar-DZ.md
README.fr-FR.md
README.ja-JP.md
README.md
README.pt-BR.md
README.ru-RU.md
README.tr-TR.md
README.zh-CN.md

I translated the RAEDME page to Arabic language.
-----
[View rendered README.ar-DZ.md](https://github.com/HouariZegai/ant-design-pro/blob/master/README.ar-DZ.md)

Arabic language

---

src/global.tsx

增加对https环境判断，解决在http页面报错的问题
关联#7275 #6845

增加对https环境判断，解决在http页面报错的问题

---

package.json
src/pages/ListTableList/components/UpdateForm.tsx

close https://github.com/ant-design/ant-design-pro/issues/7330

⚡️ performance: use profrom

---

src/pages/user/login/index.less

fix: fix stylelint error (#7731)

---

.github/workflows/preview.yml

fix: revert to pull_request

---

src/models/login.ts
src/typings.d.ts

Like https://github.com/ant-design/ant-design-pro/pull/4887 in v2.

fix: redirect with deploy on non-root path

---

src/app.tsx

fix use history.type = 'hash' open link error.
修复在使用 history.type = hash 的配置时打开链接导致页面异常问题

app.tsx dev links use Link

---

src/app.tsx

reset v5-app-tsx-links 

---

config/config.dev.ts
config/config.ts
src/components/GlobalHeader/AvatarDropdown.tsx

fix(webpack config): compile fail

fix(webpack config): compile fail

---

src/components/RightContent/AvatarDropdown.tsx

fix conflict type and eslint waring!

---

src/components/RightContent/index.less

https://github.com/ant-design/ant-design-pro/issues/8667

修复小屏幕下 头像变形

---

src/components/NoticeIcon/index.tsx

close https://github.com/ant-design/ant-design-pro/issues/8721

fix: fix NoticeIcon state update on an unmounted component

---

src/services/ant-design-pro/login.ts

fix: fix http Method Not Allowed

---

src/pages/user/Login/index.tsx

I fixed a small mistake in Hump naming, I hope it can be adopted

docx: defaultlogin to defaultLogin

---

src/locales/bn-BD/pages.ts
src/locales/en-US/pages.ts
src/locales/fa-IR/pages.ts
src/locales/id-ID/pages.ts
src/locales/ja-JP/pages.ts
src/locales/pt-BR/pages.ts
src/locales/zh-CN/pages.ts
src/pages/user/Login/index.tsx

将密码错误提示中不对称的括号（ant.design) 改为 (ant.design)

fix(pages.login.accountlogin.errormessage): 修改提示中不对称的括号

---

mock/user.ts
src/app.tsx

close https://github.com/ant-design/ant-design-pro/issues/8053

fix(request): no use defualt showType

---

config/config.ts

All blocks: fix routes error

---

src/components/Footer/index.tsx
src/components/NoticeIcon/index.tsx
src/pages/Admin.tsx
src/pages/Welcome.tsx

refactor: modify all function types in jsx to `React.FC`

---

src/pages/list/search/articles/index.tsx

修改前：
修改后:
Signed-off-by: lzskyline <lzskyline@foxmail.com>

修复select无选中时的显示BUG

---

Dockerfile.dev

Update https://registry.npm.taobao.org to https://registry.npmmirror.com, Please refer to https://zhuanlan.zhihu.com/p/430580607.

update https://registry.npm.taobao.org to https://registry.npmmirror.com

---

src/components/HeaderSearch/index.tsx

fix: type error

---

package.json

re. #9824 
Add `swagger-ui-react` dep to package.json.

[Resolved BUG] Module not found: Error: Can't resolve 'btoa'

---

package.json
src/components/RightContent/AvatarDropdown.tsx

具体可参看 antd 的这个 PR：
https://github.com/ant-design/ant-design/pull/34559

Update to antd 4.20.0 for `Menu support items`

---

package.json

移除重复的依赖swagger-ui-react，并且swagger-ui-react应该是dev依赖

chore: remove duplicate swagger-ui-react

---

.github/ISSUE_TEMPLATE/question.md

Reverts ant-design/ant-design-pro#9953
-----
[View rendered .github/ISSUE_TEMPLATE/question.md](https://github.com/ant-design/ant-design-pro/blob/revert-9953-patch-1/.github/ISSUE_TEMPLATE/question.md)

Revert "Update question.md"

---

src/components/HeaderSearch/index.tsx

修正：点击搜索不会聚焦的bug

---

src/app.tsx
src/components/RightContent/AvatarDropdown.tsx

https://github.com/umijs/umi/issues/8618
这个iss

fix: fix  location get error

---

src/e2e/baseLayout.e2e.spec.ts

Lodash used only here. So you can replace uniq function by Set and you can remove lodash.

You might not need lodash

---

src/components/RightContent/AvatarDropdown.tsx
src/pages/User/Login/index.tsx

fix: You may NOT need # b9163ae and # 00151a6

---

config/routes.ts

chore: update router params description

---

config/defaultSettings.ts

fix: 更新TS 声明

---

package.json

rename umijs/facrib to umijs/fabric

fix import umijs/fabric package error

---

src/app.tsx

fix: hide SettingDrawer in production environment

---

src/app.tsx

chore: symbol

---

src/app.tsx

chore: one import

---

src/app.tsx
src/pages/User/Login/__snapshots__/login.test.tsx.snap

The props  that `pro-layout` provided is `bgLayoutImgList` rather than `layoutBgImgList`, maybe this is a typo?
Alternatively, if this prop is not documented, it is acceptable to remove it.
BTW, committed Login page snapshot looks like coming from Welcome page, I've updated them in this PR.

fix: fix wrong pro-layout props.

---

src/pages/list/basic-list/index.tsx

fix: solve dropdown label display unexpected

---

src/pages/profile/advanced/index.tsx

feat: optimize style

---

src/pages/list/search/index.tsx

- fix: 当前激活状态丢失
- fix: 点击跳转路由错误

fix: solve search-list tab route work unexpected issue.

---

README.es-ES.md
README.md

Hi! 
I have translated the README. 
Regards 🐧🐧!!

docs(README): translation to Spanish

---

README.md

As I follow the current documentation step by step:  
1. `npm i @ant-design/pro-cli -g`  
2. `pro create myapp`  
3. `cd myapp && npm install`  
Step 3, the following error occurs:  
```bash
...
> ant-design-pro@6.0.0 postinstall
> max setup
😄 Hello PRO
info  - [你知道吗？] 全局数据存储，在 React 之外修改数据怎么办？试试一键上手 valtio，详见 https://umijs.org/docs/max/valtio
Using openapi Plugin
info  - generate files
info  - Preparing...
> ant-design-pro@6.0.0 prepare
> husky install
.git can't be found (see https://git.io/Jc3F9)
npm ERR! code 1
npm ERR! path ***/myapp
npm ERR! command failed
npm ERR! command sh -c husky install
...
```  
Because `postinstall` requires `husky` (dependent on `.git`) to be installed, the documentation has been optimized to complete the entire documentation step, adding a step to …

Optimize Usage documentation

---

package.json
pnpm-lock.yaml

fix: add comma in package.json

---

src/locales/zh-TW.ts

fix: zh-TW.ts error

---

src/access.ts

The original link was inaccessible with error code 404, updated to a valid document link

update: access statements updated to valid document links

---

src/pages/account/settings/components/notification.tsx

Hi, I have discovered an issue where the content of the title and subtitle is inconsistent, and it has been fixed

fix: 标题与副标题内容不一致的问题

---

config/routes.ts

Fix https://github.com/ant-design/ant-design-pro-cli/issues/126

fix: 404 path in routes.ts
